name: mapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy=1.10.1
  - scikit-learn
  - notebook
  - pip
  - pip:
      - rpy2==3.5.16
      - anndata
      - anndata2ri